k9s:
  liveViewAutoRefresh: false
  gpuVendors: {}
  screenDumpDir: /Users/raven/.config/k9s/screen-dumps
  refreshRate: 2
  apiServerTimeout: 15s
  maxConnRetry: 5
  readOnly: false
  noExitOnCtrlC: false
  portForwardAddress: localhost
  ui:
    enableMouse: true
    headless: false
    logoless: true
    crumbsless: false
    splashless: false
    reactive: false
    noIcons: true
    defaultsToFullScreen: false
    useFullGVRTitle: false
    skin: transparent
  skipLatestRevCheck: false
  disablePodCounting: false
  shellPod:
    image: busybox:1.35.0
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi
  imageScans:
    enable: false
    exclusions:
      namespaces: []
      labels: {}
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: -1
    textWrap: false
    disableAutoscroll: false
    showTime: false
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  defaultView: ""
